spring:
  jpa:
    generate-ddl: true
    show-sql: true
    properties.hibernate.temp.use_jdbc_metadata_defaults: false
  datasource:
    url:  jdbc:postgresql://localhost/postgres
    username: postgres
    password: postgres